/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/parse-ramen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AIによるラーメンメモの解析 */
        post: operations["parseRamen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ParseRamenRequest: {
            /** @example 韮崎のラーメン屋である韮崎家、醤油で星4 */
            text: string;
        };
        RamenData: {
            /** @example 韮崎家 */
            name: string;
            /**
             * @default []
             * @example [
             *       "家系",
             *       "醤油"
             *     ]
             */
            categories: string[];
            /**
             * @default null
             * @example 4
             */
            rating: number | null;
            /**
             * @default null
             * @example 山梨県韮崎市
             */
            location: string | null;
            /**
             * @default null
             * @example こってりしてて美味しかった。
             */
            review: string | null;
        };
        ErrorResponse: {
            /** @example エラーメッセージがここに入ります */
            error: string;
            /** @example ERROR_CODE_HERE */
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    parseRamen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRamenRequest"];
            };
        };
        responses: {
            /** @description 解析成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RamenData"];
                };
            };
            /** @description リクエスト不備（入力テキストが空、または不正） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description LLM解析失敗（データが仕様を満たさない） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部サービスエラー（Gemini APIへの接続失敗） */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
