/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/parse-ramen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AIによるラーメンメモの解析 */
        post: operations["parseRamen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register-ramen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ラーメン屋情報をDBに新規登録する */
        post: operations["registerRamen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ParseRamenRequest: {
            /** @example 韮崎のラーメン屋である韮崎家、醤油で星4 */
            text: string;
        };
        RamenData: {
            /** @example 韮崎家 */
            name: string;
            /**
             * @default []
             * @example [
             *       "家系",
             *       "醤油"
             *     ]
             */
            categories: string[];
            /**
             * @default null
             * @example 4
             */
            rating: number | null;
            /**
             * @default null
             * @example 山梨県韮崎市
             */
            location: string | null;
            /**
             * @default null
             * @example こってりしてて美味しかった。
             */
            review: string | null;
        };
        RegisterRamenData: {
            /** @example 光家 */
            name: string;
            /**
             * @example [
             *       "豚骨",
             *       "醤油",
             *       "家系"
             *     ]
             */
            categories: string[];
            /** @example 4 */
            rating: number;
            /** @example 横浜市 */
            location: string;
            /** @example キャベツラーメンが最高 */
            review: string;
        };
        ErrorResponse: {
            /** @example エラーメッセージがここに入ります */
            message: string;
            /** @example ERROR_CODE_NAME */
            code: string;
        };
        RegisterRamenResponse: {
            /**
             * Format: uuid
             * @description Supabaseから発行されたID
             */
            id: string;
            /** @example 登録が完了しました */
            message: string;
        };
    };
    responses: {
        /** @description リクエストの形式が正しくありません */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description AIの解析に失敗しました */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "value": {
                 *         "message": "AIの回答を解析できませんでした",
                 *         "code": "PARSE_FAILURE"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 外部サービス（Gemini/Supabase）に接続できません */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 予期せぬエラー */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "value": {
                 *         "message": "予期せぬエラーが発生しました",
                 *         "code": "INTERNAL_SERVER_ERROR"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    parseRamen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRamenRequest"];
            };
        };
        responses: {
            /** @description 解析成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RamenData"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    registerRamen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRamenData"];
            };
        };
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterRamenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
