openapi: 3.0.0
info:
  title: Ramen Concierge API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  # --- ラーメンメモ解析 ---
  /api/parse-ramen:
    post:
      summary: AIによるラーメンメモの解析
      operationId: parseRamen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParseRamenRequest'
      responses:
        '200':
          description: 解析成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RamenData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '500':
          $ref: '#/components/responses/InternalServerError'

  # --- ラーメン屋情報登録 ---
  /api/register-ramen:
    post:
      summary: ラーメン屋情報をDBに新規登録する
      operationId: registerRamen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RamenData'
      responses:
        '201':
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterRamenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ParseRamenRequest:
      type: object
      required: [text]
      properties:
        text:
          type: string
          minLength: 1
          maxLength: 1000
          example: "韮崎のラーメン屋である韮崎家、醤油で星4"

    RamenData:
      type: object
      required: [name, categories, rating, location, review]
      properties:
        name:
          type: string
          example: "韮崎家"
        categories:
          type: array
          items: { type: string }
          default: []
          example: ["家系", "醤油"]
        rating:
          type: integer
          minimum: 1
          maximum: 5
          nullable: true
          default: null
          example: 4
        location:
          type: string
          nullable: true
          default: null
          example: "山梨県韮崎市"
        review:
          type: string
          nullable: true
          default: null
          example: "こってりしてて美味しかった。"

    # CustomErrorクラスの構造に合わせたエラーレスポンス
    ErrorResponse:
      type: object
      required: [message, code]
      properties:
        message:
          type: string
          example: "エラーメッセージがここに入ります"
        code:
          type: string
          example: "ERROR_CODE_NAME"

    RegisterRamenResponse:
      type: object
      required: [id, message]
      properties:
        id:
          type: string
          format: uuid
          description: Supabaseから発行されたID
        message:
          type: string
          example: "登録が完了しました"

  responses:
    BadRequest:
      description: リクエストの形式が正しくありません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            invalid_json:
              value: { message: "JSONの形式が正しくありません", code: "INVALID_JSON" }
            validation_error:
              value: { message: "入力内容が不足しています", code: "BAD_REQUEST" }

    UnprocessableEntity:
      description: AIの解析に失敗しました
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            value: { message: "AIの回答を解析できませんでした", code: "PARSE_FAILURE" }

    ServiceUnavailable:
      description: 外部サービス（Gemini/Supabase）に接続できません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            gemini_error:
              value: { message: "AIとの通信に失敗しました", code: "AI_SERVICE_UNAVAILABLE" }
            supabase_error:
              value: { message: "DBへの接続に失敗しました", code: "DATABASE_CONNECTION_ERROR" }

    InternalServerError:
      description: 予期せぬエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            value: { message: "予期せぬエラーが発生しました", code: "INTERNAL_SERVER_ERROR" }