openapi: 3.0.0
info:
  title: Ramen Concierge API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  # --- ラーメンメモ解析 ---
  /api/parse-ramen:
    post:
      summary: AIによるラーメンメモの解析
      operationId: parseRamen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParseRamenRequest'
      responses:
        '200':
          description: 解析成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RamenData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '500':
          $ref: '#/components/responses/InternalServerError'

  # --- ラーメン屋情報登録 ---
  /api/register-ramen:
    post:
      summary: ラーメン屋情報をDBに新規登録する
      operationId: registerRamen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRamenData'
      responses:
        '201':
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterRamenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '500':
          $ref: '#/components/responses/InternalServerError'
  # --- ラーメン屋検索 ---
  /api/search-ramen:
    post:
      summary: ラーメン検索 (RAG検索 + Web検索)
      operationId: searchRamen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRamenRequest'
      responses:
        '200':
          description: 検索成功
          content:
            application/json:
              schema:
                type: object
                required: [db_match, web_match]
                properties:
                  db_match:
                    type: array
                    description: 自分のログ（DB）からの検索結果
                    items:
                      $ref: '#/components/schemas/SearchRamenResult'
                  web_match:
                    type: array
                    description: Web知識からの検索結果
                    items:
                      $ref: '#/components/schemas/SearchRamenResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '500':
          $ref: '#/components/responses/InternalServerError'
          


components:
  schemas:
    ParseRamenRequest:
      type: object
      required: [text]
      properties:
        text:
          type: string
          minLength: 1
          maxLength: 1000
          example: "韮崎のラーメン屋である韮崎家、醤油で星4"
    SearchRamenRequest:
      type: object
      required: [text]
      properties:
        text:
          type: string
          minLength: 1
          maxLength: 1000
          example: "とんこつ醤油ラーメンで最高においしいのが食べたい。"

    RamenData:
      type: object
      required: [name, categories, rating, location, review]
      properties:
        name:
          type: string
          example: "韮崎家"
        categories:
          type: array
          items: { type: string }
          default: []
          example: ["家系", "醤油"]
        rating:
          type: integer
          minimum: 1
          maximum: 5
          nullable: true
          default: null
          example: 4
        location:
          type: string
          nullable: true
          default: null
          example: "山梨県韮崎市"
        review:
          type: string
          nullable: true
          default: null
          example: "こってりしてて美味しかった。"
    RegisterRamenData:
      type: object
      additionalProperties: false
      required: [name, categories, rating, location, review]
      properties:
        name:
          type: string
          minLength: 1
          example: "光家"
        categories:
          type: array
          items:
            type: string
            minLength: 1
          minItems: 1
          example: ["豚骨", "醤油", "家系"]
        rating:
          type: integer
          minimum: 1
          maximum: 5
          example: 4
        location:
          type: string
          minLength: 1
          example: "横浜市"
        review:
          type: string
          minLength: 1
          example: "キャベツラーメンが最高"
    SearchRamenResult:
      type: object
      additionalProperties: false
      required: [name, categories, rating, location, review, similarity, ai_comment]
      properties:
        name:
          type: string
          minLength: 1
          example: "ラーメン次郎横浜関内店"
        categories:
          type: array
          items:
            type: string
            minLength: 1
          minItems: 1
          example: ["二郎系", "醤油"]
        rating:
          type: integer
          minimum: 1
          maximum: 5
          example: 5
        location:
          type: string
          minLength: 1
          example: "横浜市"
        review:
          type: string
          minLength: 1
          example: "微乳化スープが麺に絡み合い、満足度が高いです。"
        similarity:
          type: number
          minimum: 0.0
          maximum: 1.0
          example: 0.8
        ai_comment:
          type: string
          minLength: 1
          example: "あなたの好みに非常にマッチしています！ぜひ訪れてみて"

    # CustomErrorクラスの構造に合わせたエラーレスポンス
    ErrorResponse:
      type: object
      required: [message, code]
      properties:
        message:
          type: string
          example: "エラーメッセージがここに入ります"
        code:
          type: string
          example: "ERROR_CODE_NAME"

    RegisterRamenResponse:
      type: object
      required: [id, message]
      properties:
        id:
          type: string
          format: uuid
          description: Supabaseから発行されたID
        message:
          type: string
          example: "登録が完了しました"

  responses:
    BadRequest:
      description: リクエストの形式が正しくありません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            invalid_json:
              value: { message: "JSONの形式が正しくありません", code: "INVALID_JSON" }
            validation_error:
              value: { message: "入力内容が不足しています", code: "BAD_REQUEST" }

    UnprocessableEntity:
      description: AIの解析に失敗しました
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            value: { message: "AIの回答を解析できませんでした", code: "PARSE_FAILURE" }

    ServiceUnavailable:
      description: 外部サービス（Gemini/Supabase）に接続できません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            gemini_error:
              value: { message: "AIとの通信に失敗しました", code: "AI_SERVICE_UNAVAILABLE" }
            supabase_error:
              value: { message: "DBへの接続に失敗しました", code: "DATABASE_CONNECTION_ERROR" }

    InternalServerError:
      description: 予期せぬエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            value: { message: "予期せぬエラーが発生しました", code: "INTERNAL_SERVER_ERROR" }

    NotFound:
      description: リソースが見つかりません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            value: { message: "指定されたリソースが見つかりません", code: "NOT_FOUND" }